name: file_selector_example
description: Demonstrates how to use the file_selector package.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_selector:
    path: ../

flutter:
  uses-material-design: true
