name: file_selector
version: 1.0.0
homepage: https://github.com/marchdev-tk/file_selector
description: File selection on both Mobile (Android/iOS), Web and Desktop (Windows, macOS, Linux)

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.8.0
  flinq: ^1.1.1

  file_picker: ^1.4.3+2
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
